version: '3'
services:
  mousser-backnode:
    ports:
      - '1522:80'
    image: moussersite-backnode-image
    environment:
      NODE_ENV: 'development'
    volumes:
      - ../src:/www/src
    networks:
      - api-net
      - db-net # => We need to manually create and declare our external network so our containers can communicate
    command: 'yarn run dev'
  mousserdb:
    image: mongo
    # restart: 'always'
    environment:
      # FOR AUTH, haven't got these to work yet
      # MONGO_INITDB_ROOT_USERNAME: 'root'
      # MONGO_INITDB_ROOT_PASSWORD: 't00r'
      MONGO_INITDB_DATABASE: 'site_document'
    # expose:
    #   - 27017
    ports:
      - '27017:27017'
    volumes:
      - ./_mongodb:/data/db
      - ./_mongodb_config:/data/configdb
    networks:
      - db-net
networks:
  api-net:
  db-net:
    external: true
    # This will return not found if we dont create it
    # via docker network create <network-name>
